### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by hartmark** [desbma/motd#1]
```
% motd -V
motd 1.0.8



% motd
──────────────────────────── Load ─────────────────────────────
Load avg 1min: 1.28, 5 min: 0.64, 15 min: 0.38
Tasks: 443

──────────────────────── Memory usage ─────────────────────────
MemTotal:   8.0 GB
MemFree:  380.6 MB ( 4.7%)
Dirty:    196.0 KB ( 0.0%)
Cached:     5.6 GB (70.0%)
Buffers:    1.7 MB ( 0.0%)
▕██Used 1.9GB██████████████Cached 5.4GB (70.0%)████████████   ▏
memory allocation of 18446744073709551615 bytes failed[1]    32
06304 abort (core dumped)  motd



```

**Comment by desbma** [comment]
To investigate, can you :
* post the output of `cat /proc/meminfo`
* run a debug build with full backtrace ie with `RUST_BACKTRACE=full cargo run` in the source directory

**Comment by hartmark** [comment]
```
% cat /proc/meminfo 
MemTotal:        8019540 kB
MemFree:          442484 kB
MemAvailable:    5906196 kB
Buffers:            1692 kB
Cached:          5531708 kB
SwapCached:        38496 kB
Active:          3661576 kB
Inactive:        3228748 kB
Active(anon):     685404 kB
Inactive(anon):   678904 kB
Active(file):    2976172 kB
Inactive(file):  2549844 kB
Unevictable:       22828 kB
Mlocked:           22712 kB
SwapTotal:       1048560 kB
SwapFree:         275676 kB
Dirty:             10144 kB
Writeback:             0 kB
AnonPages:       1341292 kB
Mapped:           134020 kB
Shmem:               708 kB
KReclaimable:     242868 kB
Slab:             394752 kB
SReclaimable:     242868 kB
SUnreclaim:       151884 kB
KernelStack:        7404 kB
PageTables:        12972 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     5058328 kB
Committed_AS:    3727712 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       29220 kB
VmallocChunk:          0 kB
Percpu:             3376 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:     1625928 kB
DirectMap2M:     6633472 kB
DirectMap1G:           0 kB

```

```
% RUST_BACKTRACE=full cargo run
   Compiling libc v0.2.69                                                            
   Compiling bitflags v1.2.1                                                         
   Compiling unicode-width v0.1.7                                                    
   Compiling strsim v0.8.0                                                                                                                                                
   Compiling ansi_term v0.11.0                                                       
   Compiling either v1.5.3                                                           
   Compiling vec_map v0.8.2                                                          
   Compiling glob v0.3.0                                                                                                                                                  
   Compiling simple-error v0.2.1                                                                                                                                          
   Compiling bytesize v1.0.0                                                         
   Compiling ansi_term v0.12.1                                                       
   Compiling textwrap v0.11.0                                                        
   Compiling itertools v0.8.2                                                        
   Compiling atty v0.2.14                                                            
   Compiling num_cpus v1.11.1                                                        
   Compiling clap v2.33.0                                                            
   Compiling termsize v0.1.6                                                         
   Compiling motd v1.0.8 (/home/markus/code/motd)    
    Finished dev [unoptimized + debuginfo] target(s) in 11.07s   
     Running `target/debug/motd`                                                                                                                                          
───────────────────────────────────── Load ─────────────────────────────────────     
Load avg 1min: 0.62, 5 min: 0.81, 15 min: 0.53
Tasks: 454                       
                                          
───────────────────────────────── Memory usage ─────────────────────────────────
MemTotal:   8.0 GB                                                                                                                                                        
MemFree:  407.7 MB ( 5.1%)
Dirty:     51.4 MB ( 0.6%)
Cached:     5.6 GB (69.9%)
Buffers:    1.7 MB ( 0.0%)
▕█Used 1.9GB (25.0%)██████████████████Cached 5.3GB (69.9%)█████████████████Free▏
thread 'main' panicked at 'attempt to subtract with overflow', src/mem.rs:136:24
stack backtrace:
   0:     0x55709029c9a5 - backtrace::backtrace::libunwind::trace::h3d39f137d452b8f1
                               at /build/rust/src/rustc-1.46.0-src/vendor/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55709029c9a5 - backtrace::backtrace::trace_unsynchronized::hcf5986a1d0af0d50
                               at /build/rust/src/rustc-1.46.0-src/vendor/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55709029c9a5 - std::sys_common::backtrace::_print_fmt::h2c7ad4fc7b131e83
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55709029c9a5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h68c1e40d505fb676
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5570902c3b8c - core::fmt::write::h26a0fba054cf05aa
                               at src/libcore/fmt/mod.rs:1076
   5:     0x5570902972e2 - std::io::Write::write_fmt::ha995a4c8c6bc16e5
                               at src/libstd/io/mod.rs:1537
   6:     0x55709029f040 - std::sys_common::backtrace::_print::he217055a87c1f227
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55709029f040 - std::sys_common::backtrace::print::h72506ec7ccc94843
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55709029f040 - std::panicking::default_hook::{{closure}}::h38604ad774a278a9
                               at src/libstd/panicking.rs:198
   9:     0x55709029ed8c - std::panicking::default_hook::h471b84bc7af03980
                               at src/libstd/panicking.rs:217
  10:     0x55709029f683 - std::panicking::rust_panic_with_hook::h85ab5cceba14f607
                               at src/libstd/panicking.rs:526
  11:     0x55709029f27b - rust_begin_unwind
                               at src/libstd/panicking.rs:437
  12:     0x5570902c1af1 - core::panicking::panic_fmt::h4a347a4fdf0d3bfc
                               at src/libcore/panicking.rs:85
  13:     0x5570902c1a3d - core::panicking::panic::hbc5ca421114da301
                               at src/libcore/panicking.rs:50
  14:     0x5570900c9a6e - motd::mem::output_mem_stats::h56f1dfc7de6d4df3
                               at src/mem.rs:136
  15:     0x5570900cb094 - motd::mem::output_swap::h75120381c55e4d12
                               at src/mem.rs:221
  16:     0x55709011b963 - motd::main::{{closure}}::h292e979b798f04aa
                               at src/main.rs:349
  17:     0x55709010ccd9 - core::result::Result<T,E>::map::h01bf733197023102
                               at /build/rust/src/rustc-1.46.0-src/src/libcore/result.rs:519
  18:     0x5570900d9cb3 - motd::main::h3d90d3bda4cede63
                               at src/main.rs:346
  19:     0x55709011d47b - std::rt::lang_start::{{closure}}::h9c3b0d089562ef23
                               at /build/rust/src/rustc-1.46.0-src/src/libstd/rt.rs:67
  20:     0x55709029fa53 - std::rt::lang_start_internal::{{closure}}::hb8e98fe8f632dfe8
                               at src/libstd/rt.rs:52
  21:     0x55709029fa53 - std::panicking::try::do_call::h6f2671248f5c4024
                               at src/libstd/panicking.rs:348
  22:     0x55709029fa53 - std::panicking::try::h344107437d1e83cb
                               at src/libstd/panicking.rs:325
  23:     0x55709029fa53 - std::panic::catch_unwind::h145e12ddd29bae55
                               at src/libstd/panic.rs:394
  24:     0x55709029fa53 - std::rt::lang_start_internal::h34986349101de4a9
                               at src/libstd/rt.rs:51
  25:     0x55709011d457 - std::rt::lang_start::h9256a8bfb576a5ba
                               at /build/rust/src/rustc-1.46.0-src/src/libstd/rt.rs:67
  26:     0x5570900dabaa - main
  27:     0x7f535a7df152 - __libc_start_main
  28:     0x5570900bc0ee - _start
  29:                0x0 - <unknown>
RUST_BACKTRACE=full cargo run  24.78s user 1.85s system 238% cpu 11.168 total

```

**Comment by desbma** [comment]
Fixed, thanks for the report.
